import { Inter } from "next/font/google";
import "./globals.scss";
import { ReactQueryClientProvider } from "./components/ReactQueryClienteProvider";
import AuthChecker from "./components/AuthChecker";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Gerênciamento de Estoque",
	description: "Generated by create next app",
	icons: {
		icon: "/images/favicon.ico",
	},
};

export default function RootLayout({ children }) {
	return (
		<html lang="pt-br">
			<body className={inter.className}>
				<ReactQueryClientProvider>
					<AuthChecker>
						{children}
					</AuthChecker>
				</ReactQueryClientProvider>
			</body>
		</html>
	);
}
